config/routes.rb
Rails.application.routes.draw do
  resources :tableros
  get 'usuarios/:id/publicacions', to: "usuarios#mostrar"
  devise_for :usuarios
  resources :etiqueta
  resources :publicacions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "publicacions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/etiquetum.rb
class Etiquetum < ApplicationRecord
  has_and_belongs_to_many :publicacion
end

app/models/publicacion.rb
class Publicacion < ApplicationRecord
    has_and_belongs_to_many :etiqueta 
    accepts_nested_attributes_for :etiqueta
    has_many :usuario, through: :tableros
    has_one_attached :foto

end

app/models/tablero.rb
class Tablero < ApplicationRecord
  belongs_to :publicacion
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :publicacions, through: :tableros
  accepts_nested_attributes_for :publicacions 
  enum rol: [:fotografo, :administrador]
  after_initialize do
    if self.new.record?
      self.rol ||= :fotografo
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:mail, :encrypted_password])  
    end
    def permitted_administrador?
        if !current_user.administrador?
            redirect_to etiqueta_path, alert: "No tiene permisos para editar etiquetas"
        end
    end
end

app/controllers/etiqueta_controller.rb
class EtiquetaController < ApplicationController
  before_action :set_etiquetum, only: %i[ show edit update destroy ]
  before_action :permitted_administrador?, except: [:index, :show]

  # GET /etiqueta or /etiqueta.json
  def index
    @etiqueta = Etiquetum.all
    @publicacions = Publicacion.all
  end

  # GET /etiqueta/1 or /etiqueta/1.json
  def show
  end

  # GET /etiqueta/new
  def new
    @etiquetum = Etiquetum.new
    @publicacions = Publicacion.all
  end

  # GET /etiqueta/1/edit
  def edit
    @publicacions = Publicacion.all
  end

  # POST /etiqueta or /etiqueta.json
  def create
    @etiquetum = Etiquetum.new(etiquetum_params)

    respond_to do |format|
      if @etiquetum.save
        format.html { redirect_to etiquetum_url(@etiquetum), notice: "Etiquetum was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etiqueta/1 or /etiqueta/1.json
  def update
    respond_to do |format|
      if @etiquetum.update(etiquetum_params)
        format.html { redirect_to etiquetum_url(@etiquetum), notice: "Etiquetum was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etiqueta/1 or /etiqueta/1.json
  def destroy
    @etiquetum.destroy

    respond_to do |format|
      format.html { redirect_to etiqueta_url, notice: "Etiquetum was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etiquetum
      @etiquetum = Etiquetum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def etiquetum_params
      params.require(:etiquetum).permit(:nombre, publicacion_ids: [])
    end
end

app/controllers/publicacions_controller.rb
class PublicacionsController < ApplicationController
  before_action :set_publicacion, only: %i[ show edit update destroy ]

  # GET /publicacions or /publicacions.json
  def index
    @publicacions = Publicacion.all
  end

  # GET /publicacions/1 or /publicacions/1.json
  def show
  end

  # GET /publicacions/new
  def new
    @publicacion = Publicacion.new
    @etiqueta = Etiquetum.all
  end

  # GET /publicacions/1/edit
  def edit
      @etiqueta = Etiquetum.all
  end

  # POST /publicacions or /publicacions.json
  def create
    @publicacion = Publicacion.new(publicacion_params)

    respond_to do |format|
      if @publicacion.save
        format.html { redirect_to publicacion_url(@publicacion), notice: "Publicacion was successfully created." }
        format.json { render :show, status: :created, location: @publicacion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publicacions/1 or /publicacions/1.json
  def update
    respond_to do |format|
      if @publicacion.update(publicacion_params)
        format.html { redirect_to publicacion_url(@publicacion), notice: "Publicacion was successfully updated." }
        format.json { render :show, status: :ok, location: @publicacion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publicacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publicacions/1 or /publicacions/1.json
  def destroy
    @publicacion.destroy

    respond_to do |format|
      format.html { redirect_to publicacions_url, notice: "Publicacion was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicacion
      @publicacion = Publicacion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publicacion_params
      params.require(:publicacion).permit(:titulo, :usuario_id, :foto, etiquetum_ids: [])
    end
end

app/controllers/tableros_controller.rb
class TablerosController < ApplicationController
  before_action :set_tablero, only: %i[ show edit update destroy ]

  # GET /tableros or /tableros.json
  def index
    @tableros = Tablero.all
  end

  # GET /tableros/1 or /tableros/1.json
  def show
  end

  # GET /tableros/new
  def new
    @tablero = Tablero.new
    @publicacions = Publicacion.all
  end

  # GET /tableros/1/edit
  def edit
    @publicacions = Publicacion.all
  end

  # POST /tableros or /tableros.json
  def create
    @tablero = Tablero.new(tablero_params)

    respond_to do |format|
      if @tablero.save
        format.html { redirect_to tablero_url(@tablero), notice: "Tablero was successfully created." }
        format.json { render :show, status: :created, location: @tablero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tablero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tableros/1 or /tableros/1.json
  def update
    respond_to do |format|
      if @tablero.update(tablero_params)
        format.html { redirect_to tablero_url(@tablero), notice: "Tablero was successfully updated." }
        format.json { render :show, status: :ok, location: @tablero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tablero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tableros/1 or /tableros/1.json
  def destroy
    @tablero.destroy

    respond_to do |format|
      format.html { redirect_to tableros_url, notice: "Tablero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tablero
      @tablero = Tablero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tablero_params
      params.require(:tablero).permit(:fecha, :publicacion_id, :usuario_id)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def mostrar 
    @usuario= current_usuario
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/etiqueta_helper.rb
module EtiquetaHelper
end

app/helpers/publicacions_helper.rb
module PublicacionsHelper
end

app/helpers/tableros_helper.rb
module TablerosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/etiqueta/_etiquetum.html.erb
<div id="<%= dom_id etiquetum %>">
  <p>
    <strong>Nombre:</strong>
    <%= etiquetum.nombre %>
  </p>

  <p>
    <strong>Publicacion:</strong>
    <% etiquetum.publicacion.each do |e| %>
      <%= e.titulo %>  
    <% end %>
  </p>

</div>

app/views/etiqueta/_form.html.erb
<%= form_with(model: etiquetum) do |form| %>
  <% if etiquetum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(etiquetum.errors.count, "error") %> prohibited this etiquetum from being saved:</h2>

      <ul>
        <% etiquetum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :publicacion_ids, style: "display: block" %>
    <%= form.collection_check_boxes :publicacion_ids, @publicacions, :id, :titulo %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/etiqueta/edit.html.erb
<h1>Editing etiquetum</h1>

<%= render "form", etiquetum: @etiquetum %>

<br>

<div>
  <%= link_to "Show this etiquetum", @etiquetum %> |
  <%= link_to "Back to etiqueta", etiqueta_path %>
</div>

app/views/etiqueta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Etiqueta</h1>

<div id="etiqueta">
  <% @etiqueta.each do |etiquetum| %>
    <%= render etiquetum %>
    <p>
      <%= link_to "Show this etiquetum", etiquetum %>
    </p>
  <% end %>
</div>

<%= link_to "New etiquetum", new_etiquetum_path %>

app/views/etiqueta/new.html.erb
<h1>New etiquetum</h1>

<%= render "form", etiquetum: @etiquetum %>

<br>

<div>
  <%= link_to "Back to etiqueta", etiqueta_path %>
</div>

app/views/etiqueta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @etiquetum %>

<div>
  <%= link_to "Edit this etiquetum", edit_etiquetum_path(@etiquetum) %> |
  <%= link_to "Back to etiqueta", etiqueta_path %>

  <%= button_to "Destroy this etiquetum", @etiquetum, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trabajo2Individual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert%></p>
    <br>

    <%= yield %>
    <br>
     <%= button_to(
        "Log Out",
        destroy_usuario_session_path,
        method: :delete
      ) %>

  </body>
</html>

app/views/publicacions/_form.html.erb
<%= form_with(model: publicacion) do |form| %>
  <% if publicacion.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publicacion.errors.count, "error") %> prohibited this publicacion from being saved:</h2>

      <ul>
        <% publicacion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>
  <div>
  <p>Etiquetas</p>
   <%= form.label :etiqueta %>
    <%= form.collection_check_boxes :etiquetum_ids, @etiqueta, :id, :nombre %>
  </div>
  <div>
    <%= form.hidden_field :usuario_id, value:current_usuario.id %>
  </div>
  <div>
    <%= form.label :foto %>
    <%= form.file_field :foto %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publicacions/_publicacion.html.erb
<div id="<%= dom_id publicacion %>">
  <p>
    <strong>Titulo:</strong>
    <%= publicacion.titulo %>
  </p>
  <p> 
     <strong>Etiquetas:</strong> 
     <% publicacion.etiqueta.each do |m| %>
     <%=  m.nombre %>
     <% end %>
  </p>
  <p>
    <% if publicacion.foto.attached? %>
    <%= image_tag publicacion.foto, size: '100'%>
    <% end %>
  </p>
</div>

app/views/publicacions/edit.html.erb
<h1>Editing publicacion</h1>

<%= render "form", publicacion: @publicacion, etiqueta: @etiqueta %>

<br>

<div>
  <%= link_to "Show this publicacion", @publicacion %> |
  <%= link_to "Back to publicacions", publicacions_path %>
</div>

app/views/publicacions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publicacions</h1>

<div id="publicacions">
  <% @publicacions.each do |publicacion| %>
    <%= render publicacion %>
    <p>
      <%= link_to "Show this publicacion", publicacion %>
    </p>
  <% end %>
</div>

<%= link_to "New publicacion", new_publicacion_path %>

app/views/publicacions/new.html.erb
<h1>New publicacion</h1>

<%= render "form", publicacion: @publicacion, etiqueta: @etiqueta %>

<br>

<div>
  <%= link_to "Back to publicacions", publicacions_path %>
</div>

app/views/publicacions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @publicacion %>

<div>
  <%= link_to "Edit this publicacion", edit_publicacion_path(@publicacion) %> |
  <%= link_to "Back to publicacions", publicacions_path %>

  <%= button_to "Destroy this publicacion", @publicacion, method: :delete %>
</div>

app/views/tableros/_form.html.erb
<%= form_with(model: tablero) do |form| %>
  <% if tablero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tablero.errors.count, "error") %> prohibited this tablero from being saved:</h2>

      <ul>
        <% tablero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha %>
  </div>

  <div>
    <%= form.label :publicacion_id, style: "display: block" %>
    <%= form.collection_select :publicacion_id, @publicacions, :id, :titulo %>
  </div>

  <div>
    <%= form.hidden_field :usuario_id, value:current_usuario.id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tableros/_tablero.html.erb
<div id="<%= dom_id tablero %>">
  <p>
    <strong>Fecha:</strong>
    <%= tablero.fecha %>
  </p>

  <p>
    <strong>Publicacion:</strong>
    <%= tablero.publicacion.titulo %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= tablero.usuario.email %>
  </p>

</div>

app/views/tableros/edit.html.erb
<h1>Editing tablero</h1>

<%= render "form", tablero: @tablero %>

<br>

<div>
  <%= link_to "Show this tablero", @tablero %> |
  <%= link_to "Back to tableros", tableros_path %>
</div>

app/views/tableros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tableros</h1>

<div id="tableros">
  <% @tableros.each do |tablero| %>
    <%= render tablero %>
    <p>
      <%= link_to "Show this tablero", tablero %>
    </p>
  <% end %>
</div>

<%= link_to "New tablero", new_tablero_path %>

app/views/tableros/new.html.erb
<h1>New tablero</h1>

<%= render "form", tablero: @tablero %>

<br>

<div>
  <%= link_to "Back to tableros", tableros_path %>
</div>

app/views/tableros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tablero %>

<div>
  <%= link_to "Edit this tablero", edit_tablero_path(@tablero) %> |
  <%= link_to "Back to tableros", tableros_path %>

  <%= button_to "Destroy this tablero", @tablero, method: :delete %>
</div>

app/views/usuarios/mostrar.html.erb
<h1>Usuarios#mostrar</h1>
<p>Find me in app/views/usuarios/mostrar.html.erb</p>
<div> 
 <h3>
    <%= @usuario.email %>
 </h3>
</div>
<div>
  <% @usuario.publicacions.each do |m| %>
    <%= m.titulo %>
    <% m.etiqueta.each do |n| %>
     <%= n.nombre %>   
     <% end %>
  <% end %>
</div>